In [68]:
%load_ext kedro.ipython

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

In [69]:
catalog

{'companies': "kedro_datasets.pandas.csv_dataset.CSVDataset(filepath=PurePosixPath('C:/Users/drysd/OneDrive "
              '- University of '
              "Bath/Documents/September_July_2025/Projects_portfolio/Kedro/spaceflights/data/01_raw/companies.csv'), "
              "protocol='file', load_args={}, save_args={'index': False})",
 'reviews': "kedro_datasets.pandas.csv_dataset.CSVDataset(filepath=PurePosixPath('C:/Users/drysd/OneDrive "
            '- University of '
            "Bath/Documents/September_July_2025/Projects_portfolio/Kedro/spaceflights/data/01_raw/reviews.csv'), "
            "protocol='file', load_args={}, save_args={'index': False})",
 'shuttles': "kedro_datasets.pandas.excel_dataset.ExcelDataset(filepath=PurePosixPath('C:/Users/drysd/OneDrive "
             '- University of '
             "Bath/Documents/September_July_2025/Projects_portfolio/Kedro/spaceflights/data/01_raw/shuttles.xlsx'), "
             "protocol='file', load_args={'engine': 'openpyxl'}, "
             "save_args={'index': False}, writer_args={'engine': 'openpyxl'})",
 'preprocessed_companies': "kedro_datasets.pandas.parquet_dataset.ParquetDataset(filepath=PurePosixPath('C:/Users/drysd/OneDrive "
                           '- University of '
                           "Bath/Documents/September_July_2025/Projects_portfolio/Kedro/spaceflights/data/02_intermediate/preprocessed_companies.parquet'), "
                           "protocol='file', load_args={}, save_args={})",
 'preprocessed_shuttles': "kedro_datasets.pandas.parquet_dataset.ParquetDataset(filepath=PurePosixPath('C:/Users/drysd/OneDrive "
                          '- University of '
                          "Bath/Documents/September_July_2025/Projects_portfolio/Kedro/spaceflights/data/02_intermediate/preprocessed_shuttles.parquet'), "
                          "protocol='file', load_args={}, save_args={})",
 'model_input_table': "kedro_datasets.pandas.parquet_dataset.ParquetDataset(filepath=PurePosixPath('C:/Users/drysd/OneDrive "
                      '- University of '
                      "Bath/Documents/September_July_2025/Projects_portfolio/Kedro/spaceflights/data/03_primary/model_input_table.parquet'), "
                      "protocol='file', load_args={}, save_args={})",
 'regressor': "kedro_datasets.pickle.pickle_dataset.PickleDataset(filepath=PurePosixPath('C:/Users/drysd/OneDrive "
              '- University of '
              "Bath/Documents/September_July_2025/Projects_portfolio/Kedro/spaceflights/data/06_models/regressor.pickle'), "
              "backend='pickle', protocol='file', load_args={}, save_args={}, "
              "version=Version(load=None, save='2025-07-21T17.49.44.539Z'))",
 'shuttle_passenger_capacity_plot_exp': "kedro_datasets.plotly.plotly_dataset.PlotlyDataset(filepath=PurePosixPath('C:/Users/drysd/OneDrive "
                                        '- University of '
                                        "Bath/Documents/September_July_2025/Projects_portfolio/Kedro/spaceflights/data/08_reporting/shuttle_passenger_capacity_plot_exp.json'), "
                                        "protocol='file', load_args={}, "
                                        'save_args={}, '
                                        'version=Version(load=None, '
                                        "save='2025-07-21T17.49.44.539Z'), "
                                        "plotly_args={'type': 'bar', 'fig': "
                                        "{'x': 'shuttle_type', 'y': "
                                        "'passenger_capacity', 'orientation': "
                                        "'h'}, 'layout': {'xaxis_title': "
                                        "'Shuttles', 'yaxis_title': 'Average "
                                        "passenger capacity', 'title': "
                                        "'Shuttle Passenger capacity'}})",
 'shuttle_passenger_capacity_plot_go': "kedro_datasets.plotly.json_dataset.JSONDataset(filepath=PurePosixPath('C:/Users/drysd/OneDrive "
                                       '- University of '
                                       "Bath/Documents/September_July_2025/Projects_portfolio/Kedro/spaceflights/data/08_reporting/shuttle_passenger_capacity_plot_go.json'), "
                                       "protocol='file', load_args={}, "
                                       'save_args={}, '
                                       'version=Version(load=None, '
                                       "save='2025-07-21T17.49.44.539Z'))",
 'dummy_confusion_matrix': "kedro_datasets.matplotlib.matplotlib_writer.MatplotlibWriter(filepath=PurePosixPath('C:/Users/drysd/OneDrive "
                           '- University of '
                           "Bath/Documents/September_July_2025/Projects_portfolio/Kedro/spaceflights/data/08_reporting/dummy_confusion_matrix.png'), "
                           "protocol='file', save_args={}, "
                           'version=Version(load=None, '
                           "save='2025-07-21T17.49.44.539Z'))",
 'parameters': "kedro.io.memory_dataset.MemoryDataset(data='<dict>')",
 'params:model_options': "kedro.io.memory_dataset.MemoryDataset(data='<dict>')",
 'params:model_options.test_size': "kedro.io.memory_dataset.MemoryDataset(data='<float>')",
 'params:model_options.random_state': "kedro.io.memory_dataset.MemoryDataset(data='<int>')",
 'params:model_options.features': "kedro.io.memory_dataset.MemoryDataset(data='<list>')"}

In [70]:
companies = catalog.load('companies')
companies.head()

[07/22/25 21:46:50] INFO     Loading data from companies (CSVDataset)...                        ]8;id=402688;file://C:\Users\drysd\anaconda3\envs\kedro\lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=167674;file://C:\Users\drysd\anaconda3\envs\kedro\lib\site-packages\kedro\io\data_catalog.py#403\403]8;;\

,id,company_rating,company_location,total_fleet_count,iata_approved
0,3888,100%,Isle of Man,1.0,f
1,46728,100%,NaN,1.0,f
2,34618,38%,Isle of Man,1.0,f
3,28619,100%,Bosnia and Herzegovina,1.0,f
4,8240,NaN,Chile,1.0,t

In [71]:
companies.dtypes

id                     int64
company_rating        object
company_location      object
total_fleet_count    float64
iata_approved         object
dtype: object

In [72]:
import pandas as pd

In [73]:
def _is_true(x: pd.Series) -> pd.Series:
    return x == 't'

In [74]:
companies['iata_approved'] = _is_true(companies['iata_approved'])
companies.head()

,id,company_rating,company_location,total_fleet_count,iata_approved
0,3888,100%,Isle of Man,1.0,False
1,46728,100%,NaN,1.0,False
2,34618,38%,Isle of Man,1.0,False
3,28619,100%,Bosnia and Herzegovina,1.0,False
4,8240,NaN,Chile,1.0,True

In [75]:
def _parse_percentage(x: pd.Series) -> pd.Series:
    return x.str.replace("%", "").astype(float)

In [76]:
companies['company_rating'] = _parse_percentage(companies['company_rating'])

In [77]:
companies.head()

,id,company_rating,company_location,total_fleet_count,iata_approved
0,3888,100.0,Isle of Man,1.0,False
1,46728,100.0,NaN,1.0,False
2,34618,38.0,Isle of Man,1.0,False
3,28619,100.0,Bosnia and Herzegovina,1.0,False
4,8240,NaN,Chile,1.0,True

In [78]:
companies.dtypes

id                     int64
company_rating       float64
company_location      object
total_fleet_count    float64
iata_approved           bool
dtype: object

In [79]:
shuttles = catalog.load('shuttles')

[07/22/25 21:46:51] INFO     Loading data from shuttles (ExcelDataset)...                       ]8;id=580511;file://C:\Users\drysd\anaconda3\envs\kedro\lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=430273;file://C:\Users\drysd\anaconda3\envs\kedro\lib\site-packages\kedro\io\data_catalog.py#403\403]8;;\

In [80]:
shuttles.head()

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,moon_clearance_complete,price,company_id
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,f,f,"$1,715.0",32413
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,f,f,"$3,405.0",14122
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,t,f,"$1,806.0",47761
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,f,f,"$1,676.0",26648
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,f,f,"$4,718.0",26648

In [81]:
shuttles.iloc[:, 5:]

,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,moon_clearance_complete,price,company_id
0,2.0,4,moderate,2.0,f,f,"$1,715.0",32413
1,3.0,5,moderate,3.0,f,f,"$3,405.0",14122
2,1.0,2,strict,1.0,t,f,"$1,806.0",47761
3,1.0,2,moderate,1.0,f,f,"$1,676.0",26648
4,5.0,10,strict,5.0,f,f,"$4,718.0",26648
...,...,...,...,...,...,...,...,...
15526,1.0,2,flexible,1.0,t,f,"$2,040.0",5816
15527,1.0,1,strict,1.0,t,f,"$1,260.0",19010
15528,2.0,4,flexible,2.0,t,f,"$4,107.0",6654
15529,1.0,2,flexible,1.0,t,f,"$2,170.0",27363
15530,0.0,2,moderate,2.0,t,f,"$1,455.0",12542

In [82]:
shuttles['d_check_complete'] = _is_true(shuttles['d_check_complete'])
shuttles['moon_clearance_complete'] = _is_true(['moon_clearance_complete'])

In [83]:
def _parse_money(x: pd.Series) -> pd.Series:
    return x.str.replace(r'[$,]', '', regex=True).astype(float)

In [84]:
shuttles['price'] = _parse_money(shuttles['price'])

In [85]:
shuttles.head()

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,moon_clearance_complete,price,company_id
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,False,1715.0,32413
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,False,3405.0,14122
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,False,1806.0,47761
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,False,1676.0,26648
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,False,4718.0,26648

In [86]:
reviews = catalog.load('reviews')

[07/22/25 21:46:58] INFO     Loading data from reviews (CSVDataset)...                          ]8;id=224190;file://C:\Users\drysd\anaconda3\envs\kedro\lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=653968;file://C:\Users\drysd\anaconda3\envs\kedro\lib\site-packages\kedro\io\data_catalog.py#403\403]8;;\

In [88]:
reviews.head()

,shuttle_id,review_scores_rating,review_scores_comfort,review_scores_amenities,review_scores_trip,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month
0,45163,91.0,10.0,9.0,9.0,9.0,9.0,9.0,26,0.77
1,49438,96.0,10.0,10.0,10.0,10.0,10.0,9.0,61,0.62
2,10750,97.0,10.0,10.0,10.0,10.0,10.0,10.0,467,4.66
3,4146,95.0,10.0,10.0,10.0,10.0,9.0,9.0,318,3.22
4,5067,97.0,10.0,9.0,10.0,10.0,9.0,10.0,22,0.29

In [89]:
# merge on the id
rated_shuttles = shuttles.merge(reviews, left_on='id', right_on='shuttle_id')
rated_shuttles.head()

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,...,shuttle_id,review_scores_rating,review_scores_comfort,review_scores_amenities,review_scores_trip,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,...,45163,91.0,10.0,9.0,9.0,9.0,9.0,9.0,26,0.77
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,...,49438,96.0,10.0,10.0,10.0,10.0,10.0,9.0,61,0.62
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,...,10750,97.0,10.0,10.0,10.0,10.0,10.0,10.0,467,4.66
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,...,4146,95.0,10.0,10.0,10.0,10.0,9.0,9.0,318,3.22
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,...,5067,97.0,10.0,9.0,10.0,10.0,9.0,10.0,22,0.29

In [90]:
rated_shuttles.columns
# see you have company id so can be merged with companies

Index(['id', 'shuttle_location', 'shuttle_type', 'engine_type',
       'engine_vendor', 'engines', 'passenger_capacity', 'cancellation_policy',
       'crew', 'd_check_complete', 'moon_clearance_complete', 'price',
       'company_id', 'shuttle_id', 'review_scores_rating',
       'review_scores_comfort', 'review_scores_amenities',
       'review_scores_trip', 'review_scores_crew', 'review_scores_location',
       'review_scores_price', 'number_of_reviews', 'reviews_per_month'],
      dtype='object')

In [92]:
model_input_table = rated_shuttles.merge(companies, left_on='company_id', right_on='id')
model_input_table.head()

,id_x,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,...,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month,id_y,company_rating,company_location,total_fleet_count,iata_approved
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,...,9.0,9.0,9.0,26,0.77,32413,100.0,Faroe Islands,1.0,False
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,...,10.0,10.0,9.0,61,0.62,14122,100.0,Malta,1.0,True
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,...,10.0,10.0,10.0,467,4.66,47761,100.0,Niue,2.0,False
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,...,10.0,9.0,9.0,318,3.22,26648,100.0,Niue,2.0,True
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,...,10.0,9.0,10.0,22,0.29,26648,100.0,Niue,2.0,True

In [93]:
#drop null values
model_input_table.dropna()

,id_x,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,...,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month,id_y,company_rating,company_location,total_fleet_count,iata_approved
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,...,9.0,9.0,9.0,26,0.77,32413,100.0,Faroe Islands,1.0,False
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,...,10.0,10.0,9.0,61,0.62,14122,100.0,Malta,1.0,True
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,...,10.0,10.0,10.0,467,4.66,47761,100.0,Niue,2.0,False
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,...,10.0,9.0,9.0,318,3.22,26648,100.0,Niue,2.0,True
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,...,10.0,9.0,10.0,22,0.29,26648,100.0,Niue,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15169,29334,Sao Tome and Principe,Type V7,Quantum,ThetaBase Services,1.0,3,flexible,1.0,True,...,10.0,8.0,10.0,2,2.00,46943,94.0,Peru,2.0,False
15183,49839,Rwanda,Type V5,Nuclear,"Banks, Wood and Phillips",1.0,1,flexible,1.0,True,...,10.0,10.0,10.0,2,2.00,2878,93.0,Bosnia and Herzegovina,3.0,True
15199,59798,Bouvet Island (Bouvetoya),Type V5,Plasma,ThetaBase Services,0.0,7,strict,4.0,True,...,10.0,10.0,10.0,3,3.00,8409,98.0,Maldives,9.0,False
15255,20330,Uzbekistan,Type V5,Quantum,ThetaBase Services,1.0,2,flexible,1.0,False,...,10.0,10.0,10.0,1,1.00,5701,100.0,Costa Rica,1.0,True
15265,16445,Nicaragua,Type V5,Plasma,ThetaBase Services,1.0,1,flexible,3.0,False,...,10.0,10.0,10.0,3,3.00,13728,100.0,Pakistan,1.0,False